---
- name: Install Visual Studio Code on Ubuntu
  hosts: node
  become: yes
  tasks:
    - name: Add the Microsoft GPG key to the system
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add the Visual Studio Code repository to the system
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        state: present

    - name: Update package list
      apt:
        update_cache: yes

    - name: Install Visual Studio Code
      apt:
        name: code
        state: present

